### ISSUE TITLE
Decoding error with faad2 "Bitstream value not allowed by specification"

### ISSUE THREAD

**Issue by nu774** [mstorsjo/vo-aacenc#1]
Hi,

Excuse me if this is not the right place to report problem.

I tried vo-aacenc with two songs, and one of them resulted in decoding error with the message "Bitstream value not allowed by specification".
So, I ran faad2 with MSVC debugger, and found the error was happening at the function section_data() in syntax.c, where the following check was failing:

```
    /* the sum of all sect_len_incr elements for a given window
     * group shall equal max_sfb */
    if (k != ics->max_sfb)
    {
        return 32;
    }
```

I have uploaded the problematic file here:

http://cid-a5023b3710b7858d.office.live.com/self.aspx/.Public/error.wav

**Comment by chiragjbhatt** [comment]
Hello, 
Although this is an old thread, I just want to see if there is a new version of FAAD2 binary/executable available with this fix. The one that is publicly available on rarewares (https://www.rarewares.org/aac-decoders.php) is dated 2010 but I see about reference to the fix in 2011 above. I am getting same error "Bitstream value not allowed by specification" and faad2 stops conversion after about 6 seconds. 
Thanks for your help.
chirag
